namespace Dynamicweb.Ecommerce.CheckoutHandlers.AuthorizeNetApi.Enum
{
    internal enum transactionStatusEnum
    {
        authorizedPendingCapture,
        capturedPendingSettlement,
        communicationError,
        refundSettledSuccessfully,
        refundPendingSettlement,
        approvedReview,
        declined,
        couldNotVoid,
        expired,
        generalError,
        pendingFinalSettlement,
        pendingSettlement,
        failedReview,
        settledSuccessfully,
        settlementError,
        underReview,
        updatingSettlement,
        voided,
        FDSPendingReview,
        FDSAuthorizedPendingReview,
        returnedItem,
        chargeback,
        chargebackReversal,
        authorizedPendingRelease
    }
}
